const axios = require('axios');
const jwt = require('jsonwebtoken');
require('dotenv').config();

describe('Check data function', () => {

    test('Email exist', async () => {
        const res = await axios.get(
            `http://localhost:8080/users/checkAddr`,
            {
                params: {
                    email: "lucie@mypetslife.co",
                }
            });
        expect(res.status).toBe(200);
    }, 30000);

    test('Email does not exist', async () => {
        const res = await axios.get(
            `http://localhost:8080/users/checkAddr`,
            {
                params: {
                    email: "lucie@mypetslife.com",
                }
            });
        expect(res.status).toBe(201);
    }, 30000);

    test('Pseudo exist', async () => {
        const res = await axios.get(
            `http://localhost:8080/users/checkPseudo`,
            {
                params: {
                    pseudo: "lucie33600"
                }
            });
        expect(res.status).toBe(200);
    }, 30000);

    test('Pseudo does not exist', async () => {
        const res = await axios.get(
            `http://localhost:8080/users/checkPseudo`,
            {
                params: {
                    pseudo: "lucie3"
                }
            });
        expect(res.status).toBe(201);
    }, 30000);

});

describe('Login tests', () => {

    test('User exist', async () => {
        const res = await axios.get(
            `http://localhost:8080/users/loginUser`,
            {
                params: {
                    email: "lucie@mypetslife.co",
                }
            });
        expect(res.status).toBe(200);
    }, 30000);

    test('Wrong email', async () => {
        const res = await axios.get(
            `http://localhost:8080/users/loginUser`,
            {
                params: {
                    email: "lucie@mypetslife",
                    password: "Admin123"
                }
            });
        expect(res.status).toBe(202);
    }, 30000);

});

describe('Confirm email tests', () => {

    test('Send a confirmation email', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/sendConfirmEmail`,
            {
                params: {
                    email: "lucie@mypetslife.co",
                },
            }
        );
        expect(res.status).toBe(200);
    }, 30000);

    test('Send a confirmation at wrong email', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/sendConfirmEmail`,
            {
                params: {
                    email: "lucie@mypetslife",
                },
            }
        );
        expect(res.status).toBe(202);
    }, 30000);

    test('Change the email and send a confirmation email', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/changeEmailAndConfirm`,
            {
                params: {
                    oldEmail: "lucie@mypetslife.co",
                    email: "lucie@mypetslife.co"
                },
            }
        );
        expect(res.status).toBe(201);
    }, 30000);
});

describe('Check contact mail function', () => {

    test('Form is complete', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/sendContactMail`,
            {
                params: {
                    firstName: "test",
                    lastName: "test",
                    email: "lucie@mypetslife.co",
                    phone: "0600000000",
                    object: "test",
                    subObject: "ignorer le message",
                    message: "ceci est un test de dveloppement ne pas repondre",
                    tr: "fr"
                },
            });
        expect(res.status).toBe(200);
    }, 30000);

});

describe('Check newsletter mail function', () => {

    test('Form is complete', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/sendConfirmNewsletterEmail`,
            {
                params: {
                    email: "lucie@mypetslife.co",
                    tr: "fr"
                },
            }
        );
        expect(res.status).toBe(200);
    }, 30000);

    /*test('Email is valid', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/subscribeNewsletter`,
            {
                params: {
                    email: "lucie@mypetslife.co",
                },
            }
        );
        expect(res.status).toBe(200);
    },30000);

    test('Email is invalid', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/subscribeNewsletter`,
            {
                params: {
                    email: "dayet.lucie@gmail.com",
                },
            }
        );
        expect(res.status).toBe(201);
    },30000);*/

});

describe('Check forgot password function', () => {

    test('Email exist', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/forgotPassword`,
            {
                params: {
                    email: "lucie@mypetslife.co",
                    tr: "fr"
                },
            }
        );
        expect(res.status).toBe(200);
    }, 30000);

    test('Email do not exist', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/forgotPassword`,
            {
                params: {
                    email: "lucie@mypetslife.com",
                    tr: "fr"
                },
            }
        );
        expect(res.status).toBe(202);
    }, 30000);

    test('Token is invalid', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/resetPassword`,
            {
                params: {
                    token: "test",
                    password: "test"
                },
            }
        );
        expect(res.status).toBe(202);
    }, 30000);

});

describe('Testing Avatar Upload', () => {

    test('Avatar is valid and id does not exist', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/updateUserAvatar`,
            {
                params: {
                    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjVmNGE4YjM0ZGUyYWY5MDA3OTM2YTJhMSIsImF2YXRhciI6ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBTndBQUFEY0NBWUFBQUFiV3MrQkFBQWdBRWxFUVZSNFh1MTlDWmhrVlhuMmUrNjl0YSs5TXRNOURMTXdNTXlBSURLeWlDc2dST1dQdTBGalhGZ0VNVkZqRW1NU3Q1aVl4TjhzdU9JZ2ljYTR4S2o1RXg4M0VFRlFFQmxFazlrWVp1bFplcG1lWHFwcnI3dWQvL25PdWRWVjNWM2RYZFZWdmMyY2d6NWkxN25uM3Z1ZDg5N3puVzk1UDliZDI4dWhtcEtBa3NDU1NJQXB3QzJKbk5WTmxBU0VCQlRnMUVKUUVsaENDU2pBTGFHdzFhMlVCQlRnMUJwUUVsaENDU2pBTGFHdzFhMlVCQlRnMUJwUUVsaENDU2pBTGFHdzFhMlVCQlRnMUJwUUVsaENDU2pBTGFHdzFhMlVCQlRnMUJwUUVsaENDU2pBTGFHdzFhMlVCQlRnMUJwUUVsaENDU2pBTGFHdzFhMlVCQlRnMUJwUUVsaENDU2pBTGFHdzFhMlVCQlRnMUJwUUVsaENDU2pBTGFHdzFhMlVCQlRnMUJwUUVsaENDU2pBTGFHdzFhMlVCQlRnMUJwUUVsaENDU2pBTGFHdzFhMlVCQlRnMUJwUUVsaENDU2pBTGFHd2wrTldtV3dXMFVnRWpMSGx1TDI2NXpRSktNQ3RrQ1dSeVdVUmkwUmIralNPNHlCZnlJc3hvK0VvbUtaQTExSUJMMkF3QmJnRkNLMzFsMmpJWkNmRXNMcHVJQlFNb1JVYlVxRlFnTzNZazQ4YkRvV2g2M3JySDErTldMY0VGT0RxRnRWaWRtVElaTk5UYmhBS2hXRTBDWTVNSm8xSjVCSy9OZ01DZ1FEOFB2OWl2b3dhZXc0SktNQ3RrT1dSeVdia2szQmVBUWtZWXRFWS9iSGhwNlJoc3JtTXVMUmpReWRHajQ1TWp1RXpmQWdHZ3cyUHFTNW9YZ0lLY00zTHNDVWpDTUI1NE1pTlpsSE1GaWZIOWZzRENQZ2IyNVU0NThqbXNwTmowdTZXT1pXQm1TdUpjWDArUDRLQlFFdWVYUTFTdndRVTRPcVgxYUwyTE85d0hlZDBDdFVQbkdIa3lQQ2tvWU83SExGWUFvelZ0OXRadG9WaXNZaElleFRCV0ZDT0NjRE1tY2lja3VxcllmZ1FVanZkb3M3cjlNRVY0SlpVM0xQZmJBYmd2SzVtemtKbWVHSVNNSkZ3QkpxbXpmdlU2WFJhdUFKSW5TeURUYXFzZ0ZXMGtCNlNZNUtCeGpDTWVjZFRIVm9qQVFXNDFzaXg2VkVtQVVjQW1VU0l0NXR4aHJGakl5QTFrVnJBNTRkL0huVndVa1hkU09NQnJnc0lyNEMzMDdtV2kvSCtNZkZiSkJTRzFxU0JwbWtCbkNFREtNQ3RrSW1XQUdIbzJOZ2hkcUhrZFRHazdzOENWU3FrbVRXUkdmR3NtWnhVelBpc1QwL2poUkpoaE52Q29vL2VyU0c1clIyakQxV01KOXpoR0RzNkNtaEFOQkpWenZFbFdBc0tjRXNnNVBsdjRmbmh5b0FERUh0K0hIcFF3OWg5WTlCWVJZV2tzOXpZTWRxWjVHNG5yWmhUbTJYSjgxdUh0N3VSNWJQck5WMEMwTm1uY2lqMFNXZTQwREE1TU5ZM0luWStCYnI1WjZyWkhncHdUVWd3WHlpQ3V3N0NZUXFkYW1JZ2xBR0hTWkRFTDAxQWE1ZURGcDhwb2RoWG1ISVdLMDRVa1J1akhYQW02TktadERDMkNBT00wQ0laT2wvWkR1Z2E0QURqRDZaZ1QxaVZCM1l4NlRhSXhXWUN1SmszVTlkT2xZQUNYQk1yd3JJZEZJdVYzVUpqT2lLUnlBTDhacFZJRTJIa29KM3I0Z1QwcmdxS3VlVWk5VkFLckhxM3N6aEdUNHdJVmJCNmR5SjFzdjNzRGpDZENVRDYyalFrWDlnaFZFZlJYR0Q4b1hIWTQ1VW9GTzRDWTBkSDRQZjdFQWdvSDEwVHkyTE9TeFhnbXBEc2RNQk5Ec1UwYVlpb08zWlJScHI0Z243RTE4aHpXZlVPVi8ySXVxbGo5S2VqVTNhNzhlTmpjQjBYMFdoTTJFUW9ZRm02RjBqdDVPaDhUZmNVUTJWNVBPdUVoZFNqS2NDTDluSmRqdkZqbzRoRllsTXRtMDNJU0YycWRyaVdyWUV5NEdpSGlaMlZSR1lvQlQ0dEtvVENxQ2ljYXU0bUFSZnA4SHhtdE1OZEVZY2VuY1A4YjJwSS9Xd1VjR2tYWTNCTE5zWUh4a0h4a2tiRUwzWXoxM0xBZmVSN0s4QXUwRzdHQkRETHU1eW1hM0JkRjB5NEdjcitQYm1ya2tXMG5HRmdhRG9NbjA5OFFNZ2xJWGZaK3Z5QkxSUDJhVEtRMnVHYW1NanFhUHl5S2tpcVdTR1ZRMkVpWHhXaUpZT1NDUXkxRnlvRHhUMU9HamtZUS9JbGlhbTdqTUNCQTlnNjB2dlRHUDNWQ095Y0pjMzVUWjBmbXhDQXVKUkF5RVI4cHMvbmEzYXcwLzU2QmJnbXBwZ3NodG04Rno1VnRnaFdqMGRXd2VFMFN2blNKQ2gwVFo3enlqNDF1WjNRRHBlUkxnSFBjdGgyWFJKZ05uakp3UENEdzhnZW8wRGtPUjZXTmk1U0lSbEF6OFY4UUhoakFNWTZDNnpkQVhSeXhOa3dlamlpMjMwSXJER2d4UjB3bnd1TmpwMTBYNWZCeldqZ0tSM0ZQZ3ZtcUEwM3g0QnNFTm1mK0pBN1VBSmNUUmhoeFA0MlI5U0xpTmNVWjhIcTJOQW1oSDJhWEtvQTE4UkV1cHdqSitJVk9UbzJkczArRWdmc2tvTlUvNWcwWkZCWUZhWGhoRUxlU21mSTVOSWlLb1FXYyt6U2Roejcva0U0UldmR21KeFVRbzJqN2JlRDhHMUx3N2ZCQlh3T21DUGl3U1J3QUFHaThBWkFKMXNKaFdHMldnTTBHR0F5bUFjTkZIZEZjUHlETnJpRHlmZXJmbkJ5YXdSRElXaU1uZkcrUGdXNEpnQkgyMGs1cmFhc1VzNDdIR2RJRFl6RE1XM3AreEl1QlIxR3dvZnNlQlpXUVFZWGx4c3RVZ1JkZEgrNEFEMUc0UExPWUY0SFVtRlpFb2h2QXhqWk9xYitQTy9qdExRRGFaUmNoOTNIY2VqVk1kaWpaZmlYNzBLQUkzL2Z3aklnV3Zxc3l6U1lBbHhUZ3ZjQVIxSCswMVJLVXJwQ08ySndpdzZLdXdzemR4amFjV3hndEo4aVB5cTdrOURVeUNnUnRORHoyWnpvVTkzb01sOGJFTDBRQUdsc3l3bXcrV1JIZmorNG1MaTNFeWYrMHBxaGdzYkNVUy9lYkw2QlRwL2ZGZUNhbk10eURHVDcrazZVWFdSa3FZeGNPYzFBUWhyWVFSdldrQzM3TWFDWXNaQTdWUWxNSm92aDJyOEFqSTN5WEZodVpJaU1Yd1FZMVdHV1RUNzNrbC91R29EaDRPREx3aWp0MWFiay9FWEM1RUtaUHlCN3laOTVFVzZvQU5la1VET1pqQUJQNTRadWNHKzc0UUdPeUtYZSthelcrQzV3N092SEoxTnZ5RlIvOXVkTndEQ25PS2Y5NXdEaExWV3h6RTArNjRxNTNOWnc4aE5Cak55alYrMXdsR3piV2s2WEZmTytWUStpQU5ma3JPUUxCVGlPamNTYUpJeWdUSE1KWDBrTFo1b3U2TjBuLzdTSjBTZUhKNjJKeVRjN2lMNkFYQWhlQndaRUxnSjgzWXRnNkdqeVhWdCt1YzV3NnBOaERIK216TFBDUkZMczZleGVVSUJyY2hYWnRvMUNzVERGYVIyK0tpQk0vZFBieWUrZmdwbVNMZ0xhRGRmZFhRQzBpaVhTdnhZSTA5bHNKWi9MbXBSWHpjczV3NEhueFdDZDlIN2x3T2thMDZrQTE0SUZORFdYRGFnRnVPUGZPQ0ZEODhuc2Z3MUQvQTJTcGF2Y2tpOGdhMGdMSG1iVkRzRlFPdVRId1dzRG5scDllcXFZQ25BdFdLQVVKVUtPN001TnBBZk9CTnlKYnd4QStzK0FzejVSaEpFd0s0bWdEdEIrTFRuT1d2QWdwOE1RR3JEbm5OamsyYTVXK3RGcWZrMEZ1QmJNWHFGWWhHUGJhRCtuUXdBcGZDWEZUa3FWOHVoWGowMWE0TlorSVFPTmtNV2tHc244UU9KNUNteTFwbURmamdqY01YbTJpNFNqRFFTQ3QyQkNGM0VJQmJnV0NWZWt4SGl1Z2ZBVk1xUnA4TDlPaXFCaDJ2MTZQcGVERm5BcjU3TUFrQ1N3TFdzY1pJdGVmakdHY1JqNmJvb2c5NlRjK2srWDVGZ0Z1Qll0RmdKY3JETU9mOVNQOEk0d012c3lTTzFPQ2VDZDliRUNqTFhXSk5qSUp0SjIzVEpIaGJUb3ZSZDdtTDQzeFpEN2hmd3FuUTdxcFFKY2kxWk1vVkNFWlp2bzNOZ0YvNllRQmg4NExrWk8vbzZMeURYWnlsMFlrSGdKcFBQN1RMTkdOaXBybWM2SFF6Y2tVVHprQ2swaFBnZVBTNlBETDBkL0JiZ1dTWjBXQXpuQnV6WjFZNlR2bEJoVmozT3MrYi9TTVY1dTBjc0I0L1QzNzdaSXF0NHdMc09lTFRGaDVhV3d0K2dxZHBBcndOVzFOTHlrVE9wTHFTL0NqOGJGRjFmWE5GRFdBQzBFeWh4Z2hnYkhza0hKbld0M3BrUUtXN2t4SFVpOHFLNGJxazQxSkxEMzNDUTRkOFV1TnlXOWFSVkpTd0Z1MXNsaTRLNHI4OTFtYTU1elcyUkhhMHlvaVVROVJ6dGE3NmRjSURqMTJ1UU5BS3E0ZTFiUk9sbitSK1dBdVN1T1ozNUhCbnFYNlNTVy84RWFld0lGdUdueW1rd3FyZjY3ekxZVS96SDhHbUpkQ1dpK0tzZVpTUDRFeGs5SWJoR3kvUGZlUGJVYUR1c0JFaGMwTmptcTl6UUphQXk3ejRrSkRjUHZyNGU2WXVWSlVBRnUycHhNVnJFUkNjME12ckFQc2U1NFZRWU5KZDV3NkFrR0ZnV01iaCtZUm9oMDBmL3RreUlGcGZlZUhLVlBUeGs1U2M3dFZpZUIwZzRyN2kxeWVtVDZ5OHljMVpXMzZxWS9FV1VLa0x6b0d6YlA4N3NPc084OFNiUzBHcTJXQ25BekFFZHFJSWR1YUVpdWE1LzhWZTh5NER0YjduSXpHd1BGU2RvRlM1d3gxdDB6VlpVMHp2THkxMXE0OUljL2tzQ3ByMHhGY05lZEpYVC9BV1VkdEJyWkxYendhVU5SMXM3K0xWRndVOE9hanhhUWZMMEZmYTQ4UHc3c3V5Z090d0RCb3pJL1FkUGlQZnRDUmxhQW02NVNWcGQ1cWtvcXBiTlo2TG0xUzBZUlorVEFmOHZJMjU2N3MyRGF0TjN0eGEyTEpuRTR3LzdOYzlEWU1XRDd2dXlNelBDRkxJNmx1SVlrZGVwdm94aTVSNnJvYS80aGo0NGI3VGxEM1Z5TFlkLzVVZ2FyYlpkVGdKdXhxb2hCaTVKQ0dTTHRNUVJqZ1FvQjBCb2R2dDZaUVkvWmZYbE03SjBRV3RHNkwwNDl1N2thMEU2QWEwWFRHZmFzcHpoRFVpRTFTV1ZYUTA5bEJyRHRRTHIxS213cjNtSDZEdWNDbVVjMG5IaGJkRkxPdmZkbWtMeVdpR0JtditIdXpUR2hRWWZEVWVnaXMzeDFOQVc0R3ZOa1doWktwYUlzWmxoTm5lQnlCQzhqQUZhcGJBN0h3SCtkbE1ITDc3VVJ1S0RDeEN6T0djOEc5SXBtMnRTcU1IOGV4ek8vQjlpV2czdzJnM2lTbUwxcUQzbkI0eTYwemprc3JFMDlTZXN1ZHYxQStnZkFpVnZKR0NKZnhvV0ZjeDhwSXRRenUycWMvNThnanJ6U0w1M2g4ZG1MbXJUdVNWc3prZ0pjVFRsS25raGF6RzA5N2REOFZWOVFQeEM4cUNxUHh1WG8vODhoa1huVCs4VU1tRmRTcWp4czhycldSWlQwdmFJVHVYMG12dnl4aitJMTczbzNJc25rWkUyRE5XdDdBTlBFMEtpc2p1TmZ5N0Rsa1FwOVEydVd5K0tNTXY0am9QUzBINk4zVlNqV2U3NlVSdHZWczhlYXVyYW5Wb3F5ektzbmtrQUJicFkxWk5rMmlzV0NVQk03TjBtK2Y5RTRRK0E1dnNsS3BCTlBacEh0eTRBekYrdStNSFZINFRyUTFrSkg5NzV0TWJnbGhyNUhIMFhuQmRzUVNTUWtUUVBWODA2Tmd4MDhoTWlPeStSejBsbnVjRVk0NmxkNlN6MEJJQTMwMzBybk1ybkxKVjZnWWMyblU3Tkc1ZEJiSGJteERZVzlEcUtoQ05ncVVTc1Y0R1paalpORjZVa3Q3SWpESDZzWVRGaUVJN0RWTHhiSHdMY0hwVHA1dTRuQXBaVzYzRFJzcTYyVC9YOFNRdXJiUG5HL3pQZ1k0bTB5SFlpZU5aZEs0Y0h2ZkFzMzNueUxlS1BRQlF5Yi9tdGlzbTdBU2dZZGZSUFNQd0hHZHlhUjMrVVpuQml3N2l0cEpLNmMvY2xIdmhERHlVL0lEODVxeVJCWGdKdGpKVmFZbGIxQ2laTzduSWJnWmJyd0hmVi9SNTdmZXI5QTFzbXB1MG5pYW9ETlYxYWdFU1F3aHIyYlpWalRaZHUyWTlmZVBkNW14Z1FBMTUrekFXTnBtVW0rYlpjSjFqYjFBOURJclphNjcvZ0QwaEEwY0V1VjhlU0xXU1JmNHRZMi9takErUDBNQTdmSjhscXJ4VnFwQURmUHlrcFBUQWgxSlJnTkl0SlpPU3NFTHc3QVN0a1kvdWxKc1NCNjc1bHFuYVJoRjhQWmZmaDFZUlIrTmJNbTl5TmYvUnFlLzhhYnhLNXJyT0U0LzVGc3hTbSsxT2had1AwY0M4ZzhEUFRmSHBNRlNnQ3MrK2MwRWtROVVjc3dSTHZpb3d6SGY0OEF0M3JPY1Fwdzh5d09Da3BPazV0Z21zWFM0VGJHajQyQmNRMlJ5elFrYjZQY3Q2a3RlYzBDVnQ1OGx6Q0dmYzhPd3AyWWhRREY3Mkw3TTlrNVRlcnozV0s1ZnM4K0JkaDlFZlMvVHhZb1dmZmROQkxiWm4rYS9OUEEwSHVUS0R6dHJwb1NXd3B3ZGF5dU1qT1hQK2hIekt2ZlJnQWNQU290Z2owZmQ4R21tZURwbzV4WURNQ1ZuOWZXc1AvU0NCd3F0a0YrOVJqSEJVL2xwTU43RHY5VkhhKzdyRjFHSHdRR2I0MktEOW4ydzBTSU8zdlNvTmtQcEw0ZXhhblBhNEl6SnA1SUxPdXoxM056QmJoNnBFUkZEb1did0N2alMydWNNWXdlT1NXc2dIUitnejcxL0taU2Nlb1U3UFJ1QnBENk1UQjZWeFNidnp2M1R1M2tnTXhqUVA4N1ZrOXNwUUpjM2V0QzFoR2dsSjB5Tzljb0ZhT2Y1ZnltaFlINEhCYTJ1bTk3Sm5hc014dGVXRGZ2QS9ydm9PRHkxWEdPVTRCcllFR1RkVENiemFMdDdBNVpKM3RnRkV6bjZQbDhac1lvV2pzUWYzWURnNnV1QzVJQTdZYjk3NUNHazNnMDF2S0VqQVU5MUJ3WEtjQTFLRkhMc2xBc0ZzRVp4VEV5K0xmYTZQckRxbkN1R0JDN1FOUXRoTThyZE5qZ0xWVDNPaVhnNmtENmg4RFFIeVhoWkYzRW9xUmFybXhIdndKY25aTmIzWTBBWjlreWRidjNvd0RXU3BkQTVCS3ZKc0JxekVsYmdCeVcvUkltejN2REg0bkNHaURHVDRiSUNnL3pVb0JiNEtvcEo2cjIzSk1GNHk2MEtCQy9mSUdEcWNzV0pnRU5TTjBQRFA5ZENOWWhuOUE0VmpyQmtBSmNBMVB0MkE3eWhWeWx0cGxMQWN0eWR5T2V5Wm9XYktvTDk4c0VEcnhPMXRMZTltdktWVnZaYWs4RElsbldycVMycCs4SE1sOUxJUDBRcWZnUVhDY3J1U25BelRNNzlOV2tjMXVCMG5XOFRQREUyZzZNSFQ4bGdoaDc3OG1BOHM4U0w2dzkwTkczaEpGOXhBQUwyK0FGQ2dkajJINlFxUE1rMlpCcVRVakFVeWxMRDdkaDVOOGNrZDVERE0wcnVTbkF6VE03NlhSNnNuQmk3S3c0eVBudDJpN0crOGRFWUh2UEY5SUliUU1DYTJjT3hGMERlODhOd2JmZUFUTWNZVWt4anhtQ1NrOGtpSzZDU1A2VnZIaUoveVQxRUdEL3NnTW52eWpQMUNzOXBsSUJicFlWbGMvbjRSQmpqVmQvdTNORGx5QVBvdjlNREtkRXpRQXQ2V0x0SjdLenhrd08zdGFKc1FkTStEZVlBbHorc3kyWUovd3crL3pZOW5RR1RLbVdUZUhaemdQWlI0SGM5eEpJL1RkeGc2b2RyaW1CTHNmRmxRd0JhV0dPcjAzQUYvSUJyZ3RYTTBCbGdFZDNqY1BPV1FnLzEwSGJXM05JWGwvN1NmZHNqa09QT3pCNlRhRk9FaE96azlaZ0hRMmcrMC95Nkx6TlhJNVhQRzN1V1R3QkZKOEdSdjh4ak9JK1F3RnV0YzFzWlZlamZZMmgvWngyYVNBUkNkOE12azBpcGd0RFAvWUlnLzdSQlF0N08xeU5sOTJ6TVFhankwSHdnb0xZMmNCbDVyalpaNkQ3RG82dVAxNzVGQWdyZVE0enV3Qm5BaGoreXlpc0U1b0MzRXFlck9uUGxzbEtlandCTFYxRCs5bVNpTVJsTGdLYnFFNVpoU0p2Nk1mRDRyZTFPelBRTkk3a0xDUkJ1emRIb0FkOU1NNHF5YUU5STRsMTFJZXU5NVRROWZ1bDFTU2lsZldzSEVnOUtDWUlnMzhZaDV2ajhQc0RDUGhyTTZ1dGxJZFhaN2lxbVNqNzFrUUc5OGFxcXZaa1VJd3lHR3NsWXNxQU8rdmVEQXlIWTdZMG5OUVBBdWkvTXdEL1JyTlM4NXR6bUVmOXVPRHBIRFNmOHBBM0F3VHl3Y0ZnNkw5bDlTU2hLc0JWemJpSWxjeEpOYzhJR0Vpc1RVNWREeFN1dFpGaDZBRlpIYWQzWjFvd0JTZGZPdnV5MmJPUnpuRWNlb2ZNbVhGU1BxRUdiWDhtcmNvTU40RzJNaTBESEliK094VGdtaERsOGw3cU9PVGNsckdSZ1hBQTBlNnBqbFN0aytIVUxrckxxVGk5RTlkT1pjNnJmZ04zT0l4OVYxS0dOZ2QwSmdCNi9rOXRHTDM1NXZ4d0RuR3FXTFd6dXNzVTZIVCtQRTFkRDVSOGFoNm5hV0FZRk1ITEs5OGxJSTRyM2IyOUt1eGhHc1p0MjBHaEtFSG5GN1VGcWhJYk9jUG9VWEo2VjJnVmt1VDBuc2w2VUJuVllUajBzaVRNZmh2blBWeUMzdDY4ZGRJK0hNZjRkMTEwdlRjN3RiQWpNNUQ5Wmh6OW43SngzZ01GTVAvcFdhNkhxUFVvNENEMTlSQnlEL3BBMXVYVndFK3BBRGZMaHVxNEx2TDVuTnpwWWtGRU83d0loakxnS05QN3Mxa3dueXRjQmVGemwzNW4zcjBwaXJZYkRQUitMZ1hvdFByQzJQTXNEdis1d0xuZnorRDRtOXF3L2ovR1Yzb0FmY09Db3h6d3REQ1k2T2kvUFNRQ0NtS1JPZWpmRzc3RDRsMmdBRGVIYkNuNmZDSXJZeVdEc1JBaUhaUnZ3ekRxVlRoZDg2VU1kSk5UdEJiYVhySjRrelRYeUhzMngrQllEblJOQnpTR2RWL0pJWEcxSTBDMmIwc2JMamhZQTNCa3F3bjZBTk5xVHExZGpsY3VBT245RE82NERFTG92MjMxWkhzcmxiS09CYU5wR2lZODZybFFJb3h3TWlKVlNpbzg4ZVVNOUJJWEtwMWdXRjZHWm8wQ2crK09JL29HRTlITGkvQ1RjVlhNTEhENDJuWjB2S1dFeE8vS25Sb1V5cG5Yc1h0ckVEMGZBL1NpanVRdE05bkd5cS9ocEEyYyt1c3cxdnpkN0gyVzlKVmRZUGZXTUJnTTlINCtnOXdqQWFUKzFRK2FvMGhrZFNRZnFoMnVqaFZEaDF6SzlLWlBhakFhUWpFckE1bDdQc25CNGpMYm00S1g2VXl4SE0ybFlqTTE3czBkRFh2T2pXRDc0UkxTM3duZ3hCOUwxdGllTHhBNFRSeStQb1p6djJsRFh6KzFIZ0s5ZzNrb2lJT3ZNdEQrdXdHc2VSK3BySE83TUlpTVZqaE5XaENRUGZTQkpOYjhMUkVJVmJFaDZZQXpHTUhCM3paZ0Q3bm8rV0llQTdkR1ZnMjFRbmxkS01BMWdKQkNzUWpidGtSRWd5Z2k4VUlnOWliNTlmZDFBNUdMR2hoc0tib3k0T0NMa3lqMVVmbGpHK3MvcVNIMC9DeU1zdUhWQW5hZkY4UDJ2aUlZOTR3cjVGRCtjaFQ5ZjZsaHc3ZlNpRnpDc0h0VEJCY2V5YzRPSmc0OGZWVWM3VGZxNlB6VGNWRjZ1WFl6c09lOEFMYnZ5ODhnWFNyM0o0d2RmbmtiTm4xdkFzeVl5dGkxZTFNTXZaL0tJSFZ2Ryt3UkRuUEFCZE0wUk1PclkzY1QzeU5scFd4czVRdWE4V3hHZ0U1cnQ3RDJid3RpQUNydDNVRlZUbGRaNDVrdzlsNXM0SUtqYVdnT2NPQ0tPTXhoamszZnp5QzhWYjdNZ1NzVFdQZXBBc0k3WmxwWGliUDF3QlZoZEgvWVJPR1hRVUZOSHIyV2NnYW5HYjg1Y09vVENmQzFSVXpjSGNhV1I4ZHJTb3J1My9XaExBYmVFOFgyUTlMUHlhSGg2WXZqaUYzUEVibGhBdGF4TUliLzBoQWZBRXJIS1ZmZFdRMmlWNEJid0N5VjNRWjZsR0hOUDBocWNXcUpGd3UyN2xYV0dFYi9xaDFEOTVKUER3Zy9oNkhuRTJrRU5sUUF3M01SN0wxSXgvWStTaW1xdkI0bDNPNDlQNGEybTJ5RVgxaEE5TGtFakJpMkg2SGFkRk1CWngwSTRzQXIvT2o1ZkJyRm4wZVFlY1RGZWZmTGoxVzUyYzlFc2U4NkYyZnZ6T1A0TFJGY2RMZ0FHQzc2YjI3RCtJTU8xdDJURm03RlFUS1VNTUNuK3hBTVZTcnVyQWJCSzhBdFpKWTRrTWxsWmxEa2hkWUJnZk1YTXFBOCsrelptTVQyd3pNWm5CYzRZdjJYR2NEZWJSR3MvZnNDMmw1YW04dWZNaDh1M0Y4QTkxbmlvM0xnaFFtWWZTN1cvSlVOcmF1QXhPVkVSZ3ZZZVIrZXZpaUViVWZTbGVOY0xvUTlGL3JRODhVMDRzOEhkQit3Kzl3b3pucGxCRjEvTHdQQkhZZEtEOGZSODNrVFlFVWtMazVpLzlVT2VqNENuUGdMWU4yOThxdzg4Y1VZc284emovaVZJb0ZXbHh0WkFhNytaVm4xYWE4Tk9QcW90eldoVnU3WkVnSGpCcllkck95YUMzbTh4YmhtNEFNSlpIL0FZS1hKT3NKRnVOcWFUNUpoZ3lOSkpibUllWjNXdmdQc09UK0tycHM1dWorUVE5OHI0OGorQmxqM3BReENtemdDWjN0UFp3QzcxOGZSL21JLzF0NDdpcjJiWW1oL3JZdkF5N0pvSnhuYXdPNk5WTmlEb1hkblJnUVdjSjFoa0dvSk1DQWVXL21VZUxYbVFRR3V3ZFZacGowWGwzR0czbnVtZ2tQRVZTNHdKbm44TzBFTXZNK1A0Q2FHelErc0xORHhnZzhIWHg1RTF4MzBWY25DTllENHN3Q2pSblZYMTlTd2J5c0ZDaEE0U1VacFFZcXJoYVlKMjJEWWM3WUVFSXM1MlBMREhIeTlsUUtXdk9RRDg5bmdPc2ZvZlF6RHR5ZkE0YTY2YzF2MVd5dkFOUUM0Y2dxUFB4eUFtUzlOaWFjc0Q1TjRLY0RtQVJ5M0dQSlBobEI0TElENHkwejR0K2FFanl6MUl3ckVqUUtPaG80M2NxejUyQXJ4ZjVWZmpneVo1SDZnLzlKWmJqWnRUbU1ZL1AwRVFpODFrYmdtRDBiWW02M2VnYzZ3LzlJb3R1NlN1Mld0WnFlQVo2NUt3QzBDMFZpMEZaNkhCbWE5dFYwVjRPcVJweml6U1QrY1AreEhyRHVHMGI1UmNlV2FMMlNnVjFuazV0dmhPS2NhYjU1ZG5ya2lQS24zUXk0U3QyVXc4VU81bVB2ZkhoZTdaOXZySGZTUVArb01idHdCbnJtOERkYVlnMkF3Q0o5dmxxcEJxMFJHQ25EelRKUnBsbEF5cFRtY29reEN5UkQwOVRxR0gvYXl2ajlqZ2ZtbHRhMmVNOXplYzVNQUpiVnVMa0dMdWJDT2htQ2Vjckd0TDR2MGorV3VZZllGY09wdkFtTEErTlVHenY3WDJpYjBWYkxHRnZ5WWRnWjRaa2NTcnVuQzUvY2pHR2hsZGNzRlAxWlRGeXJBelNHK2JDWXJLTTJwUlR2akNFVDlRSkRCdDQ1eTRxZ1FJeE9xWC9CRjBvSkdBY3dVeUR4YkcvK3JIZ3pjbTRWL1V3bEdod043eEFlbXV5ZzlFeEFtOXhSVkFhVkdLdW4rczlCL1YwRmtOR3RoRFJmc09iTkFsOTBOSEwyUk5BRU53VkJnMWU5czVUV2hBRmNMSFZVcUpKMVZxRm9PSGRZcFNObS9XVHJhVHYxOEJFN0JSV0M3aWM1M3k5SytiUzhIK0J4VmZpblEyT2dBdEtnRERnZDZnTUV0VUY2WFh5U2twaDZwUHVzd0dPTnRPUHArNy9EREdMWTk3SUwxekN3YzB0UW5kd1ZlUFBiVkRneCtVQVpXeDJLa1hxOHUwLzljSWxXQW15WWR4M0VsdTdMWE9zN3A4cUltR0h6blZnSUY3VkVOSTA4TkliaEZROGNmcDRBZ2tIemUzS3QzejZZWWZHZWJZQWFEdjllRTJVOUpwQXptWVIrMkg1Wk81ZFJQcHNZanVtUUt2OWs3ODFHQXZNdXgvV0J1UnRqVENzUk5ZNDlFb3JVMTdOa2kwNkFFNVoxZ1VUNTl3Q2JlUzRWMlZkWkZPVlpTL29Xalk0UEhhK0l3K0xaUStrdDFtSVVmUXcrY1FEbmFKUEdTQ2dQNmJDdU5uTWUrYzB3WVVSZE9qa0wzQVRkcndCNWprbkpCaDdERVRUdzhMUkNZQWZuN1l4ai85ektSRVFjTGNHejlueHcwS2dUWmdvRGh4dERSd3Q3RXorUlNiZThPcEg0b28xMUN3UkFNWTVraXdWdjRhcldHVW9DcmtvcHBXU2dScGJuM1VlM1kyRG41SzFFcjZKVDRUYlFGd2tDaTQrUURnNkx2MnAxcDZheWRwKzNaRkljV2RtQjB1L0QxbXJENmZUQ1AraERib1dQOTExTlRnQ05VemFOQWZ0QnpNMUJNSVFPTVhBVDlIOWJnNW1RQWRmaGlqazMvNlFVV2w3OEhxd0dBa25FUXczL2VobE5mSmJXWndXZXN2bEN0K2VaOCt1OEtjTk1rNG5LT25FY2tST3BiNStadWVZWWdFR29jK2lZRG1xZ0x3REIwUHhsT09MWThub0cvYTM3UnUwZWoyUGNTRGY1elRCRDVqWnZXNGFSMWJEc3dJWGEzbXEyc1VkSFJrUllwL1g4Q2xyY3psT24zSmg0REROTEdmRUNnQ3pDU0FLZE5nalpTRDZ5aUtqSVpaRHlLRlRFT2pVdi9wVFZQdjNtTWdQTy9UUU05eXMvdVBVZit1SWJCdDhWUk91d0swZW9pbjgxemxEY3c3R3JzcWdBM3k2d0p5cnp5VG5kTzUxU0dyUVRnTzB2RDBIM0Rvbzg0ZjlYWi9tZGpDRHF0ZUc4WDJ2b3pDM3JQSEphV09zZWR0SEJTL3pJd3E3Z3dKNDlDTWlWT1JuZm9zaXZ6ZWJsOEJBeHljeEU3V1RzUXBGREZxTWREVkFZaUFWUHp1SXRvSEFKdnVVUXdBWmErVFRRZXFjdWtJV3BBWmcvQXh6VU1maWdFdTAveklydzVnc0VRZktlcDZqamJ0Q25BemJHZ014bXFjaU1YMFdSdGdVbDFqVXZuZDRPQUV3dlMxc0NIZzlDSXVhdEZiZUlYQUsvWWV1WWZsZmhTQ1R4bE5iVHM0aUp1V21HSTFRUzl1MEJsMFFIS0tXZDBUWG5YRllZT0QzUU9vVkFPUnVvMkRBZjhWRHVHUG15RGt4dVRsQUtOQ2FOUExDWkxCSjl1QnBINWhhNk1KdlBLcUxwNlRyS25IYnEva244ejJqZlNPT0RtdmVQQ09qZ3BJUFBrSEdvcHVmVDhnSlZpMEgrK0hpZS9OeVlYUFIwTUoxdTFSYkJpb0pGbzRaUGJXckE5SkM1MUxSZG0yaU81cGNRNE1SWmQ1Nm5nOUs5TWc5L3d3UjlZMll6SUM1TjY0MWVwSGE0T21WbW1pYUlwYWNrakhYRUVZN1I0UERLaFJzcklrQ0VBQUNBQVNVUkJWSGU0T3U2MzBDNVQxRXBhL0RvREwvb3cvT2QrV09NY0YyeE1vSGVkRC8vNDNxMXdRaHBDRVQvaW5HT2laTUlwV0NnSTF4ZHRXVkovZk9GYm53VFR3cUJDbExabGdjNjM1VjJxMmpKS01ITnBOK1Fjb1hCWWNJeW9WbHNDQ25BTnJJd3lGWHFvTFlwd0lpVFp1MVlTNEI2cVpDcTRWZ0NENy9UakQ5OTJMbTU5VXkrNnFRS1EySDFvSi9KZXVyeTVsYzk2ZE82eVhSenRUd0YrSFNkSFRienFEL2F0ZUw3K0JxWncyYnNxd0RVNEJlV01nVkJiQklYeDNNb0NuQmNheGtlaStMdXhaK05scnlJTHE2ZmlOZmllUi9ySFlPb2FybnIxRTdMSTRXcHdOVFQ0anN2UlhRRnVBVkozSFJjNVFZY3V6eXFOV0NrWGNMdTZMMG5kUjdZT2hrK2ZmREZlZUUxYjNkZlY2a2lLNWJFVEtleDQzUzRZN1J6MnVLd3FKRXI2bmthaFZrMEphUUVYSzhBdFFHamxTOG9xcGlDN1dZNFdCbEJsNkV6OUZDSU03TlJETDUyYmVyM09aejA4V01DTzEvd014dFlTNGk4cUlmWE5DTnd4NlV1UTBTRGxOTzg2QjFUZFZHaFhNMnRndVFGbmprWnc4TGs2THRpYkFRdHpwSDdNY1ArbTYzRldvRFcwY1hhSjQ1TTcrL0IzWDNzYW5YZFFDcEkwKzQvdmpJRUloT2c4dU5wWXM1cVo3MVpjcTNhNEpxUllBUndsaVU3bFVHeGkyTVl1NVRyMmJJNGd1RUdEbVMvaTFMZGZQbnZVU21Namcxc2NQL2pGQU43OHAzdlJmanNGQWtpV2FSSHptUTRpOVc5KzRhNHpkQU9oMEhUK2hBWnZkb1owVjRCYjRFU1REU0ZOMFNnQXRoOWFSc0FSMUhNTWV5K01DbExVMGNldUI5d0ZrcXBNazRWVDRqZzZPSW9kYjNvSzdiZmt3QTBINFV1bHM5c2NCT3hUd05qbll5S3luOXdDaVhoVmxhRUZ5dlYwdjB3QmJnRXpUSXNyNTFYV1dRbUFvMmNnRlcvLytVbXg4QWQrZUMwQ2tYSnQ4Z1c4b0hmSjJIZ0JxVndKTzE3L0JFSXZLQ0h5b2xLRmRjdnJRMGJRd1R1aUlucUdXb3lNS2w2QTk4THZmUHBlcVFEWHlOeHlJRjhzd0hGc3o1OGxIVnJMdmNPVlg0R0NsUGRzamdwcjR1ajlMd1ZDemFYdVBEMDRqaTk5Y3hnN3YzRU1SaHREMjU5TTFBelM1amJEMFB2aWNQTmN1UGppVVFXNjJaYVZBbHlkZ0tPZGc4b1JsMm0xS1RHMVhFVm5wUUNPWG1Ya3A4RFFXeVRvaGg5K0tYU1JJdEJZb3lzb1ltdmpDKzREVllRMWZESzlvT3RER2ZqTHZKTFRoMlFNQTdmRlJjb1FuZlZpTVZJdkc3OTNZMCs2K25vcndNMHpaOVZuTmFtNmNSSElUUEdDbzBjbGM5ZEtBaHdzWU93aEhZTzNSNkF4RFNjZXZBWStqWXBlc0RrNStJVmYyd1krODIvOStORE92U0tjNi9HN3JvWnZvNDBkcjNsQ3ZHZmI3V2w1aHB2V2hHK2RaRk1FK3UrTWlYdVJ5eUFVWEYwMDVFc0JYd1c0R2xLbTNZeXl2OTBxNHdPRGhraFhWTlQ5MXJ0MHNKQ0xrNDhNcnp6QUFVZzlDQlIvbU1Ub04xMFlPa1AvL2RmQ25HRFk5dWFIa01tWndyTElLTTdTZGFWNW41SUN5UERodUZqVEdjVDMvdWxaUUlTQi9xSDJuTmMrTG41dnZ5T04wTE5uQ296S1pUbWpmdmpPTXVHV0RBeThLeVFwRWxaWm9RMEZ1S1dRUUkxN2xNMzk5Sk5HL3dRMEpOWWtBVCtIc1ZZWFgzQnFRdzlKcXJ4bGMzelBJcC8wenlWVnd3QXhGVHNjOTN6NFlyejZlbG1wa1dzY3NIVmgyaDh2NUpFK2FZSWJSSkRFd1J3WjhGeHVHOXZET0RLV3gyV3ZmMXlFaUxYZlZrQm9oelZUVTNRMERQeEJCR3MrWFlEbXN6SDA3amljTEttV3pFdkZXYWFKWElHM1ZUdGNqVW1oYzB0ZWhHNEJIYVEraXJNSWgyOURGYytHQ3d4NTNKUXJCWERsR09RSndrZVd3YlUwREw1VE9zRkhIbjBwMkt4bktoMjJXY1I0M2hLcGNPRWdVUjNvR0I0cklWOHdjZmxOVDhDeE9kcmZrVVh3RWxla3lFMXBkR016aFA1M0dlaTVPeTlxQUF6Y1NydWNoaGdaVUZTYmxJQUNYTTNGd0pETnB1WHk1QndkRzd1ZytSbjBucWxwSjJLSFcwR3hsS1Urb0hDNHlsYkJnZUdQeEdFTkFMM3J3dmlmLzNoZVEzYU1JME5aNGRPNy9JMVB3TEU0Mm0vTHdiZlZrVlFPTXhwRC82MlNaYXYzY3dYMHY1Tnk1aGlDZ2RYUGx0eks3NFVDM0N6U0pHc2JXU1dwUmJ2aUNJVDg4RzMwT0Fub2p3d1llbkJ1d0hISGg3MWJnNEsvUkZ5Z3VkaStQd3NZaTJTOTB3QVJ3RndWMmM4MVlPQm1XVTl0OU9kVWFhVCtlMVBHQUcxbmt5cmw3M0FnekJGNFRoYmFkTVp4amFIdzdXNk1mWjgwQTRiWWJ6bkkvRkFYUnFaNFhCYStWMDFsZk0rNUJoelhRVDZmbHd6TEd6dUVjY0hZcUVsckgzTXg5T0RzK1hBY0J2WnVDb05yTGdMckhjSGpVVHBNSDMxZFdqV3Byc0FpTkVwQzVWekQrR2RpYUx0elFxaC9nKzlPd00xeFhISitCQS84ODFWMXBkcVExbmh3UUZid3VleDFqMHNRUldPb01KdlJHVTFENHVVTTBWZE9DS3N0R1dBR2J2Zm9FOG9FUmVRTUYveVNxb252dE9LbG5Ic2haTE5aa0R2WGRSeDBiVDVMMHJsMUdVREl3dEREUkxIQXNQM3d6TkpTUlBwS0J5TC9laXBnNklLRk9OeThEdk5JQU9mL3R3L0doU01OcjBCYTBCTy9CSkJoc0ROVU1JMm8reHd3S3RkRDBWeTA2d2lySTBQL08yaFhrY1VWMTN5dWhLRjNoWVJQYmZ6eEc4RHFTSy9oSlExOW81SmUvVG12L2FVSUhvbEZhY3hLOW1vbWsvYkE2eUp5VVJESmQ0MmczNnRPV3YxeUNuQVZhU2pBMWJIc3l3eGV2cUFQOGJXQ25CSXVjekIraEhoQlpsb3BpUzE1M3preCtEZVV3QWdYSXV4SlJuMll4dzM0T25TYzkvT0pxVXhnOHp4SDdnZnQ2THVUZGtycFdKNFNQaVVQbS9DdlorajhZRTRBOE9TZngyRkxyMFVGSXh3WWVlUTY4VXp6dGI3akU1Sm1qd09YdmVhWDRsbW5BcTR5Z2t6S2RRVWRuMGdxOTZ5NHNnZnRqTXB3VXBhV0F0eDhLOC83dlF3NncyOGcwWnNVdThqb3Nkb3FwWFBTd1A2cnd2QnZzS0MzbVhER0tnUTZQSy9CT21WZys2SDZDeTcydnorQW5vOFEyN0pKSkk3aUxNZ2R5aElJNDRsL3VSd2YzbmtJUDNoMGRKSUl5K2ptU041a1l1UlRzZ0xQSkRoZDRMb2RIZmpHWFpmT3ExWWU3UnZIdm1NVzN2U252eW5qWmxiQVVZZFNxUVRUa2xXR3FGRk1wU3p4cFZUSzZpV21BRmNuNENZWGxXa0tGYk5qWXpmR2lOUEVoU3dpWDlXY3NSRDJQOWNQLzNvVC9oNFQ1b0FFbko0MFlmV0ZRUVVHdHg5dXJpaUhPKzdIdnN1Q2VPSkxWNEJGWE1EaE9ITEV3bXZmLzVSM3hxenNiQis3Y3dzKytObG5KZ20xUmg2OWJ1WmJlNFlXMStFaWR2TFBQcjBmNU96LzdsMFg0OGIzL0VaY085c09WeDZzMnAxQ2FpUTUxclA1bkRyRFZVbGJBYTRCd0ZGWDJqQnMyeEtSS0NJb3ZvWmJ3QnBrT0hBMXFaUW1qSFlYOXBnbXpsdiszZ0t5ajhiUjluODA5SHd5MVZUZUdsWGlJUlE4K2FVcndTTmxPbWFJSExibjMvd3JGUE9rZnNxWGUrTHJPM0E4eGZHcTIzZUpQNDJXQVVlYXJzTlFkRndnRGR6d25sL2lmdy9LYzlsMzc3b0VhM3Q5TUVzY1Y3MXhsd2U0K1kwZmduNGluNVZWYjd4UXVLa3Fab01DUDgyNks4QXRZRUtGeTRET0xZSWZidVlPUjMrbk9nSytjMnd3c2taNjNJL0VIbGM4N01PMncrbW1PWGxvZkJwazVMN3JZUmtsSEQrVmdhYkpReGM5MzkvZjFZOXYvR3hBdk4ydWJ6NUgvTzhEOStYdy9udjM0L2dQcm9NNzRlTDZEL3dDKzQ1a3dUZ1Q1NjY3M3JzTlYxMFdBbnp5QTBHMWsrMEN3eFcvSjJNcDZ6VitURDlpTGtERXArMGxDbkFOVHExbDJTaVdaTVZUMFJpVmo1cXBIajd6Z2lSS3h4MEVObm1oVUZTVzZvZ1B3VXNzYlA1L3hNcmE0STJuZGQrOU1VNmVCb3crZmdOZ080S1BuSGdqancrT3dkVURLSmtPbnY5N1Q4QzFpRXRTaG9hUW0wT1VSZEIxdUxEd3dDZXZSUHhjRHAwMDRoQVR6bTFkZHhFSVJiRTJic0JGRWQrNmJ3THYvT3ZkSXE0eXFvd2Z6VTJhY2d2VUx6L2FOY2h3UWo0NGN1WjJiT3JDV044SXdsdDkyUGc5bVRWUTNiakxzUDlaTVZGd2thNmw4NUIvcTRrdDN5dDY5ZWJxdkxkRjladmNHVVhwaGR1Qk1ZdzhjcjF3TzFRYVI2Rm9ZWGk0Q001c1hIYlRyL0REdXk5QmUzY0F6REdoV2NEbHYvdHJQUEh2enhWTXpKRlFBSjFCQTY2bUN4V1prZS9CQy84L1BKakJ0VzkvRWhOcFMxYTJVZEgvZFU3YTdOM1VEbGVIQ0t2TFdKSEJwUE9jTHZCMkg4WitQWWpJMVE0MmZIa1dVdjh5OVhjNkNKN0lpeDJwMFoyTlc4Q1JWeVhROVU0Z2VuMGF6TXR2bzFwejFFWitYanRHa2s1MWZRTXBVQ1IvMzBrVFc5WUhzYjRuanI1ajQrQ0dnWTFuUmJ3azJ0cUVrNjVtNE9qeFlWejJ1aWVGNmhvSlJhRlZCVGJYSVRiVnBZWUVGT0RtWEJZTTZheDMzcUt5U2o0ZGlkNDI4SFlYNXJDTlhIOGE1OTZySWZDaTFPSXZMc2ZBbmkxaHJQK2NnOWdOT1FqQUNiL2F0U0xWcGxiamxCUjZLb05TMFlFVERHSkxoMSs0RlFhRzB1anBtcHZjOWRTNGlYeTZnR2ZmSkozZW9XY0I5bDYvdDh2Vkh4NjIrSUpaWFhkUWdKdGx2c3hTQ2FXeVg0bDc4WlFSUDNpWEs1ekFZMDlRNVJ5R2JYMTVNS0pjV096bUdXZ0dmNzhkb3o4d3dWeE5HRHBHZmo1M0pVaUtwVHd4bE1QYWFBaEdtSXdoVTJNdGF3SVZISDM5YVJRS0RwNy9saWZGTmUzdlRNTWVEaUw5TGI5S3VXbGlyaFhnWmhFZW5kT3llZW00N1Zndk03eDUwZ1dvckJQbkdIdGlmSGt5QlJoUWVEeUN3emRwdUdKN083NjM4N0o1cDU5ckdsaXBCUGltUnh6UHZKUzA0TDZURStMTStFZC9jd2dQL1dwVTVNcDEzQ1lOUXhTUVBYNVBRUHJrRkZuUXZMS2Yza0VCYmc2UjVYSjV1S0o4S0VEbGgzbW5WN0pwRW5DOGFRZDJ3elBtWFdBUHhmRDBWUnFHSHlIZWtob21UNW5DMTFENEdKMHZoOGJ5U0pzRnZQWmR1OUYvVWthT2hKL3ZJTGl0Y2s1MVV4R2t2cUdyblc0Qms2Y0FONGZRcXVud0VtdmFoRW9tUU1jMWpEMHhBbiszaGkyUExjSDViWlpuekQ4VXhaRzNheGg1N0hwcFhheHE1TXplOW9xZklwTzNzZWZiTDBZMFppQ2MwQUhDVUhVaFJnYmtTdzV5cHl5Yy82WUhoVStPZ0JvTU9paVdwRHVoN1Iwei9ZWWpPME13RUVBazBocVc1d1dzM1ZWNWlRTGNQTk5HbTBRMm0vSElnN3JCMTdpWTJEME9KKzlpMjY5TXNFVHo1WUtiV1RrSFg1UkE2UVF3K3ROcmEwZXVhSURsY054NDU1TTRjQ2lMaWF3bExhVWludG9MbGVIQWVXZEhjTzNWM1hqTGF6cWhNNGI3NzUvQUIzWStMWHg0YmJmS3JJRXBqUkVKYkZ6NDVzcE1aczI4eDVseXJRSmNIVE9kenFURm9rcjJ0a01MQUdPSHg1Ym4vRmJqV2NsdHNQZjhPTzc5MENWNDVRMUVCOUZBYzF5a2loWlNtVHk0VzVYTmJnUFBlY012aFJzaitDd1g0U3ZsV1JibE1zV2V1cHI1WGdMV0NWNTNCRW9EVDNiYWRsV0FxMk5xS1ZRcG01Tk83L2IxSFJnOU9pTCtmZHZCR2hIL1RCZHNYMU15Vk9xNFJ6TmRUbjQ4Z3BGN2RZdytkc09DYWM2SjcrVG9ZQVlPNXpDNWk2dGV2MHNFSDNmY1NUUUw4dWxDTWtJTUJTcHRUSnFucTJIczdnamlndUpjdVFycW1VTUZ1SHFrUkJ3NTVDWXd5OVhoR1M0NGtvVkdaWFpGdVYyR0k2K0lvdmcwQlVCcDROekY5bWZTVFFVbjEvbFlzaHNueHVVWUh2L3lDM0h1RmpLakxxeGxMQnNqcDNLNDhSMi93ZUJZQ1hxUUlmRVcrVkZoSVNDNHJUSnVudnpoTGpDMk00NUFNQWgvSFJiUWhUM1Y2WFdWQWx3RDh6bEpuOGVyckpNYXNHOTdERzVPUTJoSEZzNHBQOHdqZmtTdWRMRGhhNTRxMXNBOUZ0cDEzL1lrN0p5TjhTZXZCNUhCTHFUMW5VekRMSnE0NHFaZmlSMjg3YzRNbUMxM0xzRkhXYVYxa28ybStCU1ErWThFckZGaVdwNC9rMkFoejNTNlhhTUFOMjFHWmFRN3NSUUREcVd0ZUVFY3VxYUJ6bkxVdHUvUEFUNVpvU1ozWHdoOTcvRER2NmtFLzlrbG1NY0Q0S01CV0htTzdRZVdybERqd1B2REdQK1dnZEdmM1NDaS9CdHRwRDcyRFdYd3RqODlnUDg5bEJKcUpCRy9VdE5pUU9DOG1TT1dEakJrSC9TanNNdVB1S0kycjB2a0NuQlZZaUtXTHNHTlAwZnJlTFdPTmYvWHM5cnBQdXhlSDRTL200TkZIR0Zrb091dGZwODQvMncvTUV1TVpWMVQwMWdudDZoajMvWUlUdjdzZWhpTkVoUXhIVWNHeG1HWEhGenhwbDNpeG0wM1o4QU1XWnlEem02MWdzZElWSVdmUkRIK2RRMHh3Y3lsem5Ienpab0NYRmxDSE1qa0ttazJkQmFqS2puQnRnQU1YeEQ1a1l4Z3dOcEdaek92bWMvb2VPYjZpS0JTZ01haHgydzRhWjlJdzRsYzdtREQxNWNPY1BSSWxDTjM2TWZYSVVtbGlCdG9SUGlhTFJRRk81ZlkzWDFBMjl2bGV4b2JBRi9IN0lNVm5qSXc5cm13bDNDcUFEZWYyQlhncWlSVVBxTzFuZDhHQkczaHA3TEdIR1JQNU1UT2RlR1I3SlNDOGdldWlNTTZ4Ukc1TWd0cmtQaERHR0JwTUFkMEdZRlNCenZXZkJQVXlPOTdOc1p3NnI3cmdRakhmLzFzQlAvbjhuYm9RUzkrY3BhQlhIQWNQcFRGWjc1MkZGLzU0YUR3TjdiZmtSVXN6ZlE2WVRxNzFZNk5GaVB5bElHQlAxYUFxM2VlRk9DbUFVNDNkQ1RQYm9NYk0xRTZhU00vbEJkV3h3dVAwRzQxOVFzK2VGc0h4bjVzd3IvWkJHd05UbHFIazlLdzdtTkE0bzFMZDM0cnZ3THRjQVBmdlE2QkRvRHJITjkvWkF6dit2QnZNSkdsekhPcTRFRlJNaDZBcWtPLzZNRHFmUnlpejNmZ3B6QXVTc09yVWJoanhzSWFqS1AvUTFBN1hKMklVNENiQXJnc0FwRUFvcDFSVEF5bllCZHN1Yk1SY1NzVndaaW1NWkVmYXUrVzZKUy9uL3U5RWdMYlRaR0J2WlNORi96WWUyRVF3eis1SG5xZ0V1YkZkY0F1V0RnMmxCT3FJaXNub0ZzQWkzSHdvb1BudnZIWElsdWNBTmwrRzFsV09meGJBWDIrcUMwR1RId25oT3dQZlBNU0RDMmxMRmJ5dmM0NHdGV3lBT1JYbldJQk5TSWJJWDdWYkJhUjlpaHlvN1E3TWJtejllWEowVGE3V2tVNExCbUEzd1V6M0lZVFRGdTFPREpmVGVEWWh6aEdIcm9lekZjam1KbmlKME9BbFFPT2owMU1FajlmZi9PVEdFMFRSUVBRZm1kYS9POXNWc21aejhvdy9rOEo1UGU2Q25CMVR1UVpCN2pxVWxRVkdjbGFhVlNVdnJ4ZEJUZTUyUHdqMnRucWxPUXlkenY2Nmc1a2YyTmg5SkViQUcxMnR3QlZ3VGsyVE01c2hyKytad0QvZWQ4SkFiTGtiVGxvdWdNUXFmVEZkYjRNQS9wdmxWRW04MUhvMVRuaWFkL3REQVJjRm9aZlIySnRFaWJMQzFKVk82T2hjRXFXcDZMV3M3T0F0dXU4SU45VnNnVElZRUpHanJISFh5cHB6MmMwRG01emtIT2JuSXcvZlRpRDkzMTZuK2pWZG1zSlRLTjhPWm5aWFhmamtOVG14T2lsSE45MWllMjBCWnh0T3lnVTg5UElieGlJRDc5alV5ZE01R0dsSFJSSFNsSlFSSFQ2Y2h1SjF4ZVFlQUZmTnRXd3JsbWIxc2tjQko1NVhreFFtSTg4VEJWeXBqVk82ckdEdnFFME9HZjR0Mitmd2wzZk9DTGV1ZTJ0SnBpL0tFTzN0amQyZC90RUFDYy9TclFMSWZoVWFGZGR3anR0QVpmSmtOOU1FNm9pdFlBL0lCWkZvVlFVYXFKajJsNmFDa1A4RlRaaU4rWVJPRTlENkJ5WmNMcWFXdC92QjVEN2ZnRDMzL3NjWExxTnF2eFV2UUNIb0lyb0h5bUNPUTdlOC9HRCtObHZVdUlkazIvT1E0dlkwTThDL0djMytNWU1HSGhuSEpTdEVJdFE5dmNxRTFxRHI5dXE3cWNsNEVUaWFDNkhqbk02QkhhS0V5WGtKeXB4aldRNElTdDU1L3RMQ0p4bmlYcHRpZWVKVW1pcmFtZWpIWXFxblo1NGd5U0YzZlh0WjZNckdrYzA1aGNBSUF3TVpRcklwMDB3Ym1QSFRVOEordytWSVc1L1Y0N0MvUkc4Q0ROcnZkV3h1cWdrMXNCdGt2bExuZC9xRUpqWFpSVURydXlOOVJ4TG5oK0pITGs1cjRnRXhlN0w0Q1NQRzVJeGRIK0F3ZGlZQnVNYWpBNEg0VXZFTVc3cEl2dnJuNXQ1ZTdvbU1QRUF3OENkTVVEbjJQVzF5OFY3TUVhRXJqcnNQS21MT29KcEhkdHUvb1VrZ2ZXN2FIdHJEc1pHRGwvbnZMZVl0WVA1aTA2YyttZFRhQTUrZjZWWXljSkhQRE91WE5HQVMyZHFSR3RvREJxUnNSTEF2TUl3azhyTXBGUFgreGVOb2YyM0RRU3VHWVZHYTRLQWxRRGlWM2lHUE5yUlZxa21SQWFTaVI4RCtXOTJZdnpISnU3KytIWmN0cVhLY1VZMUVNQng1UnVlRURzYTdZQWR0emh3ZVFHQmkvajhQcmE1MXI5am9QOE9HVDlXTC8zNW1RR24rZDl5UlFPT0huOUtHU1N4aThsZHF4eno1K3ZRNE9vVzRsZnJDRjVkQUE5WjBpcE9iamFIUVk5eVJDNENXS0xLd3Q4a3pmZ1VzUkluSktXd3pCSCtOUDgwTk5iREpiRGRMejhXVkhpUkFrVjIvZnRsQUxrMVhLSlVZTGpqdy92eDZ3UEV0MEsxeVUwa1hrR016d0FMUXFpUnpYeG9TZzkwWU9RYkpuVERRRGpVWU9CbVk2OTYydlZlOFlEejlFSGhsS1lGRTdpQW8rTmRNcENZMUNleDJtZ0YwdUdFMUtrb0VEN2ZDN2dsNEMzMkRtYnA2UCtUQ0hyK3Nma0NIZld1cnZGSEFWWUE4azlFTWI1VHc4dXZXb09QL2tFUFhJdmhwZzhld0tHakZQUHB3bmV1ZytoMWVma3Q4T1FRbkNYeXY5NTdVNzhUdDhRbWl5NzZmWDZoVWlwZWsvb2t1RG9BNTcyTG9Cd3YwcGVhb2UzdEpZU3ZJbCtaZERvbHJwR2RsbkNqS1IrRFlZMXpQTE1qZ1EzM3BSSGVQRE1Fckw2cHFLOVg5dGVBVFJ5MER0Qi91OXpkUHY5bkYrQ09qKytiakpPa1hZY28vanE4ZkxieXlHUzhqTXhQWXpudmcvQ0JLQVkrUmp1Nzk4RWpWbXBEVjd2ZHZKSmJwVFcrYy9rY3FBNFpvV3ZOMzlqUVl5WVF0WkY4d1JMc2FEV0U2bVNBN0M4Wmp0OGN4YnA3TXdpZEJ3UTJlblIwZFV4Q1BWMG93enJ6RzhDVlZZNHgvdmtZOGsvUldaWmNIak4zR1hLTHRMK2pYSU5iWHNORFFQaUNGbjJWQktjSncvaW5FaWpzTHV2b0hENWZtUTY5bnJjNjgvcXNxaDF1eXZSd1NONS9yeXJpbWc5YTRxd1NmWkVMSTdpMDV2MVNQMURZVHlxdWhvR2I0K2o1WEFwYUJ4Qy9uR3BFdFdCUmFVRHFaOFRlSThlaWt1RW5iL0VpUENLMWF3UmtzbW0wRTF0eTFaYnYzMHhWV0Z2d1BEV0dPUG4rQk96eGl2NGVqU2o2dkZxU1hyMkFxM29iK3BxTGhVVTFBQzQxa0xoOURPMUVZRVh6MzRvRlA5Y2FwWENxQjJReUFiV0JQd3FpKzgxaEdCZVBJVWxCSDgzY254ejBHcEQ1MGRRSEVQR0xqSGFUSUlLQm1mVGxqdXZDV1p0QjVOcXBuQ3BFQWtRUkpZdlZiTTdraDhDcjhFUG51MEJnNGFSR2kvV2N5em51YVFHNHNnQk5rNWkxaUVGSE9yYTdQNjRqZW5rS3dZMjh1WVUvMnd4cFFHa1FLT3l1NmhBR1Ryd3hqblgva2dZTEF3azZNelVhQU8zdFNoT1BBYnc2YWR4aE9QV0pvTWdvbjZ0QVlqcWRSc2RiU2tDNFV1U2VubkN4QVNlM1h4OUdQaGxCNlpDWFljR0pZRWp1eHFxdDBqUGN2QlBIZ1h3aEIwZHNjZVJDQUJKdjBuSFd1N013MmlnUmJONFI2dXFRZXhxd1RzenMybjlyREwzL25CV0Y3cE5VM0tZQlN5bnhzVTc4QW1BeVEyaEs0OHpBd0MzaHliOVR4SXdnNzVrV1ZrVVczZmJiSjJiYzEyZ0RmSFMyYk5IN3p5V2t3cStqR1Bzc0piM1NXWThqTGpoUFZEdXRkcmpacHRNMFRaUk1DbEtXZWlmOXMrWjJBN0dYbFJEWVdnTDNjVEJMdWhXbXJuQWk5ZkRVUXAwSzFnUFdLWUNBUm9tY3M3WCsyMkpJdnRHSHlJdkc0TjhBaERjdmNLRXhvSGdNS0IwSGVGV1Y0L0Z2K1pIL1VYQVNPS0ZnQ0laQkQwcU5RWnpmM3BtZXNhdFRNcXFnVEdqZ0E3REFKeGVYRlhmckdQMlVkTWFya3NYZTdIVDM5aTZSK0p1WnV0WmRTMFlXeTdSZ096WXNtMUFqbzFhazdZVWpmSkVmNk1naHVzTUgzd1lUM0djQ09nT2phSTNKTURFbURDU012TXlPQnZ0WUNKbkhiTGdIUWlpY3NBU2RnWDg5UjlkZlNGS2lwT2V5YVBZdHlCYVkvMS9BR2dZY20ySDB6K0t3aVVDTTRpYkJSREp0TnB1RjBRbkVYenVUNG9GMnowZzl0QW5OUG1qNWVnY283Tk13K2s5UldmMFZGSGNaYmRYb3EzS2NNMktIcTNkbWFORTZ0ZzJLeHlUS0Fjc3k0YnE4QWtodklNRkdJTmFQRERNei9EN290T1ExVGNRd21vNkRVaW1IM3JzbDRCSXZhWDBwTmNjQzBvOEI5dkV3aGo5STNBbmVkNU1EUnErRitJMVZXMkpaQU55aksxOENsYko4UzNLVEZ2K1hZZnl6TXFQZ1ROL3BGT0RxUldNRC9TU05Rd2E5T3lYZ2ZEMUFoUHhmaTlCb1p4NzdLY1BBV3lzcE11MnZZVUJuamJvSFpEanhJazNJY1U0Y0o5UklWUmFSTzAwMHFyU0tJbUFkQjJ3cUtFUlpUdlFOSU1vR3lsQ0FqdkV2U1BYUzd3OEkzK0daMkJUZ0ZtSFdhYUhsQ2puMDNPM1ZqcVBjTTFJckYzRm5vY2kyL2R1VDRLWlkzV2k3cFFCbVREdG9FdVdLNFdWSFRIOXZ6NjFDYWljVklnbHNrTndtZE82cjY3RVpZQkxZQmtYMEpzYStGQVJLR3FqT3VMaGVZK0FPa2VWUzdRV09XS1FTSHJZSVU3QmloMVNBVzRTcHNSd0h4WHdldmZkVXpsR05XaXNYK2xnSHJrekFHdWFTWC9LV1BKaEh5YjdROGNpUVJCOFFQUVQ0TnNuZzU3bUluVW1GTFAyYVBpNVVXV2V1ODlxWmVaNVRnRnZ3U3B6OVFuTEVreVYwM1QwVkp1ZkZPTWZOOWdRSFg1SkU2YWdyZ05MK2xpSVFORnRYamxzV1NJWHZiTUNnMHVjMUhzSzFKT2dtL2owR0owMDlDRnhVN0dNNno2Q1hYN1VJYzdCU2gxU0FXNFNaRWN4Z0dwODBtdEF0RXBmTFRJYWxhTFNzOTIyTmdWc2VIQ2llbW5Ob1pHMk5NL2pQS3lGMENhbDNDeXl6VTM0SmtRSUY2QW5BV0F0bzVXTWtCNHI3QUNlbkkzVVBuZHZPek4yczFsd3J3QzBDQXNqeDdPOW02UHFyU3Yxdml2SUlybDJFbTgweUpMZGxaZFRKVms3T25kNmZBMXFRd1RqSFJPU0ZGcGhHS1FBTGJDSWRUNE1lQjR4MkhkWVJDMk4zengzenVjQTdyZHJMRk9BV1llb0U0TGFWMFBXZVN2MXZyUnVJVStMblVqVXFLY0FZOW15SUNsTjh4UnpQUUp3dnBWSVJOdmtoaFFPeXFnbGdjaGp0RFBIZmNzRWpPVUhaTUZjakMrWDQ1K0xTZlZKZCtyVmNTNXhzSnBxT1NGZ2xxeXJBTFFJQVNLWHMvYlFGQktwOFlXMUE4dEpGdU5sY1EycUEvWnNrbnY1dEdkYzRGOW1QNHpqSTU2aW1RQTBBMHVsTGM5SHhGaGNJNW1kR3FwQ0Y4b2trc2s5NnFmWTFub2tDRGlpRDRFeHZDbkF0WGdGVWxwaUNxSVhUdTV4Q1FQY2dQeGZGRXRONjlyNzhJbllsREVUV0FiNTFnTmFrTDB5OENvMHQ3UlNUYmY5elluQlM4Zy8xY1pBd0VZbFR5T2RuV2tYS2RERWhqdGpyQzlDcHloRGQxbUZJM1JNVk8yWTBHdk51TCs4cHlvQ1JLMEFZVHM3c3BnRFg0dmtYQmhPWG8vZWUzTnoyODFyM3BmVkpEdU1rRUxzSU1DaVZwc0hBTzhKYityNnFDam1renZrMWtSeExMUmdJTms3YXlnSExzbEEwS3lyeTVPTUxnd3dRZVo2TjNHTVU3cWJCMEEyRVFvdVlCOVRpT1Z2SzRSVGdXaWh0Q2x6S1p0UFFvaTdXL29PWGkxYXRvVFVJSHBIVzR3TmlsMGsvMkF6d2VjN3E2c1ZQZ0hWS1FPWVgxYnNwUStHK05veDlVNTdab3VSMHJzdWJQYnR3Q2tYdkRGanVVbjYzeWV3QVdYTkF0YWtTVUlCcjRZb1FuQ3ZFN0R5NStDaTgyVWJzRWgvUVhVVHl0emdRSzFYVXZqSXpRVDJMbjV6UDNVRHN3a3ArblprRzhnU3NjcjRkM2JjcTkyNzg2MkU0Qi93b25wREZKVVYyUEVXUnRKUkxrZ25qUzc1WUVGc2QzVU9tNHlqQTFWUml6clJzZ1JiaWE4WlF4UGJzRXZtSTEyUVdRaFdhUExKYXB1bWlGSmIvWEJlZGIzUEJ1cWtrbGdlVytUWUZ3b3dPSks0RWVBQ3dCb0g4bnRyNmFmOGRVY0NwamViRk9VL0o0RzlLaFFvcmkyVE5wYVoydUVWRFlObnBMUFB2Nk9zdjFEQ0hxcEZXZzlEajBLVFV1eml3NXE5bFpNaWtjV1cyNTZQTUlBZG92d2FZZUxoMnAvekRZWXgvUmViSmhTSmhhUVFScVE0TTRWQUV1dDVvS3ZxaUNldU1HVmdCYmxtbVdoNitLTFZuSWpNdGIyMlNQWnBoN2NjNHRLNjBUSUtkYmVmenpuRXlTTmpyVkNiQzVjREFPMlRkb2hpWHJnQUFBbFJKUkVGVWdXcVhBQlU0eWVaeXFzVFVNc3k5QXR3eUNMMjJBc2hFbFJ0aW1wNUVGL0daQzZjengxa2ZMY0pZNjlGRDFBRGY2TWZiVU95ck1CYUpnaVdDYXRrcnhhVk04aXRpcGhYZ1ZzUTBWRCtFVkRjZDhvTVZDcFBGU01RZk9SQy9Sa1AwcHBTTTJLL1NUUHR2andLVVd6TkxVN1IxSzJPaUZlQld4anpNL2hTY2c2eWZSYk1rZHl4UndZU3lPRjMwM0ZYdzFFaFgxQmlvcUk0U25iUmJrZ0ZEV0E0SnJLcEs2YkxQdGdMY3NrOUIvUThnNjk1UmpZVnlMWElHTGNnUmU1V0dpYTlMNjJndDZ5TUJMbDhzSVJRNE03T3M2NWZ3NHZkVWdGdDhHYmYrRGh3UUVTMGU2M1Q1QnFMMDd5UjdWK3R2cTBac1hnSUtjTTNMY0ZsSGtLelRrbmxNcVl6TE9oVjEzVndCcmk0eHFVNUtBcTJSZ0FKY2ErU29SbEVTcUVzQ0NuQjFpVWwxVWhKb2pRUVU0Rm9qUnpXS2trQmRFbENBcTB0TXFwT1NRR3Nrb0FEWEdqbXFVWlFFNnBLQUFseGRZbEtkbEFSYUl3RUZ1TmJJVVkyaUpGQ1hCQlRnNmhLVDZxUWswQm9KS01DMVJvNXFGQ1dCdWlTZ0FGZVhtRlFuSllIV1NFQUJyalZ5VktNb0NkUWxBUVc0dXNTa09pa0p0RVlDQ25DdGthTWFSVW1nTGdrb3dOVWxKdFZKU2FBMUVsQ0FhNDBjMVNoS0FuVkpRQUd1TGpHcFRrb0NyWkdBQWx4cjVLaEdVUktvU3dJS2NIV0pTWFZTRW1pTkJCVGdXaU5ITllxU1FGMFNVSUNyUzB5cWs1SkFheVNnQU5jYU9hcFJsQVRxa29BQ1hGMWlVcDJVQkZvakFRVzQxc2hSamFJa1VKY0VGT0RxRXBQcXBDVFFHZ2tvd0xWR2ptb1VKWUc2SktBQVY1ZVlWQ2NsZ2RaSVFBR3VOWEpVb3lnSjFDVUJCYmk2eEtRNktRbTBSZ0wvSHhlSzlybjVaenFOQUFBQUFFbEZUa1N1UW1DQyJ9LCJpYXQiOjE2MDcwMjU5OTZ9.uWM_X-Bz5zHSCx36s5C1yzn01gC4oC64kxjnsh3avec"
                },
            }
        );
        expect(res.status).toBe(200);
    });

    test('Token is invalid', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/updateUserAvatar`,
            {
                params: {
                    token: "test",
                },
            }
        );
        expect(res.status).toBe(202);
    });

    test('Id is not valid', async () => {
        const token = {
            _id: "test",
            avatar: "data:image/png;base64"
        };
        const res = await axios.post(
            `http://localhost:8080/users/updateUserAvatar`,
            {
                params: {
                    token: jwt.sign(
                        {token},
                        process.env.SECRET_TOKEN
                    )
                },
            }
        );
        expect(res.status).toBe(202);
    });

});

describe('Testing Home Information Update', () => {

    test('Home informations are valid and id exist', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/updateUserHomeInfos`,
            {
                params: {
                    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjVmNGE4YjM0ZGUyYWY5MDA3OTM2YTJhMSIsImhvdXNlIjoiaG91c2UiLCJpc19ob3VzZV9vd25lciI6dHJ1ZSwiaGF2ZV9ob3VzZV9vd25lcl9hY2NvcmQiOnRydWUsImdhcmRlbiI6dHJ1ZSwiZ2FyZGVuX3N1cmZhY2UiOjEyLCJnYXJkZW5fdW5pdHkiOiJtIiwiZ2FyZGVuX2ZlbmNlIjp0cnVlfX0.08b6xawXxnSWHO6qynIN2SAawvmKl19OTATVQAgq914"
                },
            }
        );
        expect(res.status).toBe(200);
    });

    test('Home informations are valid but id is not valid', async () => {
        const token = {
            data: {
                _id: "test",
                house: "house",
                is_house_owner: true,
                have_house_owner_accord: true,
                garden: true,
                garden_surface: 12,
                garden_unity: "m",
                garden_fence: true
            }
        };
        const res = await axios.post(
            `http://localhost:8080/users/updateUserHomeInfos`,
            {
                params: {
                    token: jwt.sign(
                        {token},
                        process.env.SECRET_TOKEN
                    )
                },
            }
        );
        expect(res.status).toBe(202);
    });

    test('Token is invalid', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/updateUserHomeInfos`,
            {
                params: {
                    token: "test",
                },
            }
        );
        expect(res.status).toBe(202);
    });

});

describe('Testing Environment Information Update', () => {
    test('Environment informations are valid and id exist', async () => {
        const data = {
            _id: "5f4a8b34de2af9007936a2a1",
            child_number: 1,
            adult_number: 2,
            allergy: true,
            other_pets: true,
            other_pets_description: "blablabla",
        };
        const res = await axios.post(
            `http://localhost:8080/users/updateUserEnvironmentInfos`,
            {
                params: {
                    token: jwt.sign(
                        {data},
                        process.env.SECRET_TOKEN
                    )
                },
            }
        );
        expect(res.status).toBe(200);
    });

    test('Environment informations are valid but id is not valid', async () => {
        const data = {
            _id: "test",
            child_number: 1,
            adult_number: 2,
            allergy: true,
            other_pets: true,
            other_pets_description: "other_pets_description",
        };
        const res = await axios.post(
            `http://localhost:8080/users/updateUserEnvironmentInfos`,
            {
                params: {
                    token: jwt.sign(
                        {data},
                        process.env.SECRET_TOKEN
                    )
                },
            }
        );
        expect(res.status).toBe(202);
    });

    test('Token is invalid', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/updateUserEnvironmentInfos`,
            {
                params: {
                    token: "test",
                },
            }
        );
        expect(res.status).toBe(202);
    });
});

describe('Testing Daily informations Update', () => {
    test('Daily informations are valid and id exist', async () => {
        const data = {
            _id: "5f4a8b34de2af9007936a2a1",
            have_adopted_yet: true,
            pet_adopted_description: "Un petit chat de goutiere",
            adoption_day_night: "adoption_day_night",
            hour_absent: 8,
            adoption_activities: "Des balades et des jeux",
            walk_number: 7
        };
        const res = await axios.post(
            `http://localhost:8080/users/updateUserDailyInfos`,
            {
                params: {
                    token: jwt.sign(
                        {data},
                        process.env.SECRET_TOKEN
                    )
                },
            }
        );
        expect(res.status).toBe(200);
    });

    test('Daily informations are valid but id is not valid', async () => {
        const data = {
            _id: "test",
            have_adopted_yet: true,
            pet_adopted_description: "Un petit chat de goutiere",
            adoption_day_night: "adoption_day_night",
            hour_absent: 8,
            adoption_activities: "Des balades et des jeux",
            walk_number: 7
        };
        const res = await axios.post(
            `http://localhost:8080/users/updateUserDailyInfos`,
            {
                params: {
                    token: jwt.sign(
                        {data},
                        process.env.SECRET_TOKEN
                    )
                },
            }
        );
        expect(res.status).toBe(202);
    });

    test('Token is invalid', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/updateUserDailyInfos`,
            {
                params: {
                    token: "test",
                },
            }
        );
        expect(res.status).toBe(202);
    });
});

describe('Testing Motivation informations Update', () => {
    test('Motivation informations are valid and id exist', async () => {
        const data = {
            _id: "5f4a8b34de2af9007936a2a1",
            adoption_why: "adoption_why",
            adoption_when: "adoption_when",
            adoption_research: "adoption_research"
        };
        const res = await axios.post(
            `http://localhost:8080/users/updateUserMotivationInfos`,
            {
                params: {
                    token: jwt.sign(
                        {data},
                        process.env.SECRET_TOKEN
                    )
                },
            }
        );
        expect(res.status).toBe(200);
    });

    test('Motivation informations are valid but id is not valid', async () => {
        const data = {
            _id: "test",
            adoption_why: "adoption_why",
            adoption_when: "adoption_when",
            adoption_research: "adoption_research"
        };
        const res = await axios.post(
            `http://localhost:8080/users/updateUserMotivationInfos`,
            {
                params: {
                    token: jwt.sign(
                        {data},
                        process.env.SECRET_TOKEN
                    )
                },
            }
        );
        expect(res.status).toBe(202);
    });

    test('Token is invalid', async () => {
        const res = await axios.post(
            `http://localhost:8080/users/updateUserMotivationInfos`,
            {
                params: {
                    token: "test",
                },
            }
        );
        expect(res.status).toBe(202);
    });
});
